const GET_REQUEST_DATA = "GET_REQUEST_DATA";
const GET_FAILURE_DATA = "GET_FAILURE_DATA";
const GET_SUCCESS_DATA = "GET_SUCCESS_DATA";

const POST_REQUEST_DATA = "POST_REQUEST_DATA";
const POST_FAILURE_DATA = "POST_FAILURE_DATA";
const POST_SUCCESS_DATA = "POST_FAILURE_DATA";

const UPDATE_REQUEST_DATA = "UPDATE_REQUEST_DATA";
const UPDATE_FAILURE_DATA = "UPDATE_FAILURE_DATA";
const UPDATE_SUCCESS_DATA = "UPDATE_FAILURE_DATA";

const DELETE_REQUEST_DATA = "DELETE_REQUEST_DATA";
const DELETE_FAILURE_DATA = "DELETE_FAILURE_DATA";
const DELETE_SUCCESS_DATA = "DELETE_FAILURE_DATA";

export {
  GET_FAILURE_DATA,
  GET_REQUEST_DATA,
  GET_SUCCESS_DATA,
  POST_FAILURE_DATA,
  POST_REQUEST_DATA,
  POST_SUCCESS_DATA,
  UPDATE_FAILURE_DATA,
  UPDATE_REQUEST_DATA,
  UPDATE_SUCCESS_DATA,
  DELETE_FAILURE_DATA,
  DELETE_REQUEST_DATA,
  DELETE_SUCCESS_DATA
};
