export const POST_REQUEST_DATA = "POST_REQUEST_DATA";
export const POST_FAILURE_DATA = "POST_FAILURE_DATA";
export const POST_SUCCESS_DATA = "POST_SUCCESS_DATA";

export const POST_REQUEST_DATA_LOGIN = "POST_REQUEST_DATA_LOGIN";
export const POST_FAILURE_DATA_LOGIN = "POST_FAILURE_DATA_LOGIN";
export const POST_SUCCESS_DATA_LOGIN = "POST_SUCCESS_DATA_LOGIN";
