const GET_REQUEST_DATA = "GET_REQUEST_DATA";
const GET_FAILURE_DATA = "GET_FAILURE_DATA";
const GET_SUCCESS_DATA = "GET_SUCCESS_DATA";

const POST_REQUEST_DATA = "POST_REQUEST_DATA";
const POST_FAILURE_DATA = "POST_FAILURE_DATA";
const POST_SUCCESS_DATA = "POST_FAILURE_DATA";


export {
  GET_FAILURE_DATA,
  GET_REQUEST_DATA,
  GET_SUCCESS_DATA,
  POST_FAILURE_DATA,
  POST_REQUEST_DATA,
  POST_SUCCESS_DATA,
};
